# Makefile.deps created Sun Oct 11 12:45:58 PDT 2020
ubigint.o: ubigint.cpp debug.h relops.h ubigint.h
bigint.o: bigint.cpp bigint.h debug.h ubigint.h relops.h
libfns.o: libfns.cpp libfns.h bigint.h debug.h ubigint.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp bigint.h debug.h ubigint.h iterstack.h libfns.h \
 scanner.h util.h
